# Generated by Django 5.1.2 on 2024-10-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_django', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CAR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='study',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SP', 'Sophoore')], max_length=50),
        ),
    ]
